### PR TITLE
New module style

### PR DESCRIPTION
**Pull request by AshtonDavis**
Hey Olivier,

Here's the work I've done.  My travis tests are failing on some rspec stuff that you've defined, I would love some help debugging that.
I haven't completely finished the documentation.

Have a look through the code.  This may not be the best way to do it, but it does seem to work better than keeping atop all of the configuration options manually.

### CODE REVIEW

**Comment by olivierHa** [comment]
I will correct travis and update to puppet module to be "0.10" compatible :)

**Comment by AshtonDavis** [comment]
Woo hoo!  Let me know if I can help.

**Comment by olivierHa** [comment]
I am on it since this morning :)
It is coming ^

2016-01-20 17:09 GMT+01:00 Ashton Davis notifications@github.com:

**Comment by AshtonDavis** [comment]
Fantastic!

**Pull request merged**
