### PR TITLE
Break arrays onto multiple lines

### PR DESCRIPTION
**Pull request by madAndroid**
This addresses #18

### CODE REVIEW

**Comment by olivierHa** [comment]
Sorry, I've merged the wrong PR about this issue. Could you update your PR so I can merge it ?
Regards

**Comment by madAndroid** [comment]
No problem :) I've rebased the PR, and pushed the changes.

**Comment by olivierHa** [comment]
Many thanks and sorry for the delay

**Comment by madAndroid** [comment]
No worries, thanks for the merge 👍

**Pull request merged**
